---
permalink: concept_configure_snapinfo_directory_settings.html
sidebar: sidebar
keywords: configure, configuring, snapinfo, setting, host, virtual, machine, resource, dataset, action, directory
summary: You must configure the SnapInfo settings for a host before you can add the virtual machine resources within that host to a dataset.
---
= Configure SnapInfo directory settings
:icons: font
:imagesdir: ./media/

[.lead]
You must configure the SnapInfo settings for a host before you can add the virtual machine resources within that host to a dataset. If the SnapInfo settings are not configured when a Hyper-V host is added to SnapManager for Hyper-V, you can configure those settings later, using the Configuration wizard or the *SnapInfo settings* action.

You can also change the SnapInfo settings after the host has been added to SnapManager for Hyper-V. However, if you change the SnapInfo settings, you must manually move all files to the new location; SnapManager for Hyper-V does not update them automatically. If you do not move the files, you cannot restore from or manage the backup copy, and SnapManager for Hyper-V does not list the backup copy.

Starting with SnapManager for Hyper-V, the SnapInfo path can reside on Cluster Shared Volumes (CSV) and it can also reside on SMB shares for Windows Server 2012.

*Related information*

http://technet.microsoft.com/library/jj612868.aspx[Microsoft TechNet: Use Cluster Shared Volumes in a Failover Cluster]
