---
permalink: concept_configure_snapmanager_for_hyper_v_for_failover.html
sidebar: sidebar
keywords: enable, snapmanager, hyper-v, implementation, disaster, recovery, primary, secondary, host, powershell, failover, configure, configuring
summary: "To fully enable your SnapManager for Hyper-V implementation for disaster recovery, you must ensure that the primary and secondary hosts have the same configuration and know that you can perform disaster recovery using only PowerShell."
---
= Configure SnapManager for Hyper-V for failover
:icons: font
:imagesdir: ./media/

[.lead]
To fully enable your SnapManager for Hyper-V implementation for disaster recovery, you must ensure that the primary and secondary hosts have the same configuration and know that you can perform disaster recovery using only PowerShell.

The following types of setups support disaster recovery:

* Stand-alone primary host and stand-alone secondary Hyper-V host
* Clustered primary and secondary Hyper-V hosts
* Cluster shared volumes (CSV) on the primary and secondary Hyper-V hosts

For example, a cluster virtual machine (VM) on a primary host must be recovered as a cluster VM, a dedicated (stand-alone) VM must be recovered as a dedicated VM, and a CSV VM must be recovered as a CSV VM.

LUNs on a secondary host should be connected in the same way as their counterparts on the primary host. That is, the LUN type (dedicated, shared, or CSV) and the drive letter, mount point, or CSV reparse point should be the same on primary and secondary hosts. With SAN restore operations to an alternate path location, a different drive letter can be specified for the LUN restore operation on a secondary location.

NOTE: Drive letters or CSVs and volume mount points are supported.

The following example shows a basic disaster recovery setup:

* Site A (primary) contains storage systems and a stand-alone Hyper-V host system or Hyper-V host cluster.
+
VMs running on these hosts reside on Data ONTAP storage.

* Site B (secondary) contains storage systems and a Hyper-V host or cluster (same as that of primary).
* SnapDrive for Windows and SnapManager for Hyper-V are installed on both sites A and B.
* The SnapMirror relationship is initialized from site A to site B.
* On site A, a Hyper-V host or cluster added to SnapManager for Hyper-V and the VMs is backed up using SnapManager for Hyper-V.
+
The policy to update SnapMirror after the backup is checked. After each backup, the secondary site is updated with new Snapshot copies of the VMs and SnapInfo copies.
