---
permalink: concept-how-snapmanager-for-hyper-v-handles-saved-state-backups.html
sidebar: sidebar
keywords: default, behavior, snapmanager, hyper-v, backup, contain, virtual, machine, save, state, shut, down, saved-state
summary: "Although the default behavior of SnapManager for Hyper-V is to cause backups containing virtual machines that are in the saved state to shut down or fail, you can perform a saved-state backup by moving the virtual machines to a dataset that has a policy that allows saved-state backups."
---
= How SnapManager for Hyper-V handles saved-state backups
:icons: font
:imagesdir: ./media/

[.lead]
Although the default behavior of SnapManager for Hyper-V is to cause backups containing virtual machines that are in the saved state to shut down or fail, you can perform a saved-state backup by moving the virtual machines to a dataset that has a policy that allows saved-state backups.

You can also create or edit your dataset policy to allow a saved-state virtual machine backup. If you choose this option, SnapManager for Hyper-V does not cause the backup to fail when the Hyper-V VSS writer backs up the virtual machine using the saved state or performs an offline backup of the virtual machine. However, performing a saved-state or offline backup can cause downtime.

*Related information*

http://technet.microsoft.com/library/cc753637(WS.10).aspx[Microsoft TechNet: Hyper-V]
