---
permalink: concept_how_snapmanager_for_hyper_v_uses_vss.html
sidebar: sidebar
keywords: snapmanager, hyper-v, integration, microsoft, hyper-v, volume, shadow, copy, service, vss, quiesce, virtual, machine, vm, snapshot
summary: SnapManager for Hyper-V provides integration with Microsoft Hyper-V Volume Shadow Copy Service \(VSS\) writer to quiesce a virtual machine \(VM\) before creating an application-consistent Snapshot copy of the VM.
---
= How SnapManager for Hyper-V uses VSS
:icons: font
:imagesdir: ./media/

[.lead]
SnapManager for Hyper-V provides integration with Microsoft Hyper-V Volume Shadow Copy Service (VSS) writer to quiesce a virtual machine (VM) before creating an application-consistent Snapshot copy of the VM.

SnapManager for Hyper-V is a VSS requestor and coordinates the backup operation to create a consistent Snapshot copy, using VSS Hardware Provider for Data ONTAP for Hyper-V VMs running on SAN and Remote VSS provider for Hyper-V VMs running on SMB 3.0 share.

SnapManager for Hyper-V enables you to make application-consistent backups of a VM, if you have Microsoft Exchange, Microsoft SQL, or any other VSS-aware application running on virtual hard disks (VHDs) in the VM. SnapManager for Hyper-V coordinates with the application writers inside the VM to ensure that application data is consistent when the backup occurs.

You can also restore a VM from an application-consistent backup. The applications that exist in the VM restore to the same state as at the time of the backup. SnapManager for Hyper-V restores the VM to its original location.

NOTE: VSS integration is available only with application-consistent backups. Crash-consistent backups do not use VSS.
