---
settings:
  name: SnapManager for Hyper-V
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
  - title: SnapManager for Hyper-V docs
    url: "/index.html"
  - title: Release notes
    url: /release-notes.html
  - title: What SnapManager for Hyper-V is
    url: "/concept-what-snapmanager-for-hyper-v-is.html"
    entries:
    - title: What you can do with SnapManager for Hyper-V
      url: "/concept-what-you-can-do-with-snapmanager-for-hyper-v.html"
    - title: List of SnapManager for Hyper-V limitations
      url: "/concept-snapmanager-for-hyper-v-limitations.html"
    - title: Data management concepts
      url: "/concept-data-management-concepts.html"
  - title: List of requirements for installing SnapManager for Hyper-V
    url: "/reference-list-of-requirements-for-installing-snapmanager-for-hyper-v.html"
    entries:
    - title: SnapManager for Hyper-V licensing for ONTAP
      url: "/reference-snapmanager-for-hyper-v-licensing-for-ontap.html"
    - title: Hyper-V parent host requirements
      url: "/reference-hyper-v-parent-host-requirements.html"
    - title: Hotfix requirements for Windows Server environments
      url: "/reference-hotfix-requirements-for-windows-server-environments.html"
    - title: License requirements
      url: "/reference-license-requirements.html"
    - title: Requirements for using the Remote Host Install wizard
      url: "/reference-requirements-for-remote-host-install.html"
  - title: Install SnapManager for Hyper-V
    url: "/concept-install-snapmanager-for-hyper-v.html"
    entries:
    - title: Download SnapManager for Hyper-V
      url: "/task-download-snapmanager-for-hyper-v.html"
    - title: Installation order for SnapDrive for Windows and SnapManager for Hyper-V
      url: "/concept-installation-order-for-snapdrive-for-windows-and-snapmanager-for-hyper-v.html"
    - title: Install SnapManager for Hyper-V
      url: "/task-install-snapmanager-for-hyper-v.html"
    - title: Remotely install or uninstall SnapManager for Hyper-V on nodes or
        hosts
      url: "/task-remotely-install-or-uninstall-snapmanager-for-hyper-v-on-nodes.html"
    - title: List and description of command line switches for silent installation
      url: "/reference-command-line-switch-descriptions.html"
  - title: Uninstall SnapManager for Hyper-V on Windows
    url: "/concept-uninstall-snapmanager-for-hyper-v-on-windows.html"
    entries:
    - title: Uninstall SnapManager for Hyper-V
      url: "/task-uninstall-snapmanager-for-hyper-v.html"
  - title: Configure SnapManager for Hyper-V
    url: "/concept-configure-snapmanager-for-hyper-v.html"
    entries:
    - title: Dashboard settings
      url: "/concept-dashboard-settings.html"
    - title: Configure hosts
      url: "/concept-configure-hosts.html"
      entries:
      - title: Requirements for adding a Hyper-V parent host or host cluster
        url: "/reference-requirements-for-adding-a-hyper-v-parent-host-or-host-cluster.html"
      - title: Add a Hyper-V parent host or host cluster
        url: "/task-add-a-hyper-v-parent-host-or-host-cluster.html"
      - title: Manage storage connection settings
        url: "/task-manage-storage-connection-settings.html"
      - title: View a Hyper-V parent host or host cluster
        url: "/task-view-a-hyper-v-parent-host-or-host-cluster.html"
      - title: View a virtual machine
        url: "/task-view-a-virtual-machine.html"
      - title: Migrat a Hyper-V virtual machine for SnapManager for Hyper-V operations
        url: "/task-migrate-a-hyper-v-virtual-machine-to-support-snapmanager-for-hyper-v-operations.html"
      - title: Import or export host and dataset configuration information
        url: "/task-import-or-export-host-and-dataset-configuration-information.html"
      - title: Remove a Hyper-V parent host or parent host cluster
        url: "/task-remove-a-hyper-v-parent-host.html"
      - title: Event notification settings
        url: "/concept-event-notification-settings.html"
        entries:
        - title: Configure email notifications
          url: "/concept-configure-multiple-recipients-for-email-notifications-in-smhv.html"
      - title: Report path settings
        url: "/concept-report-path-settings.html"
    - title: Configure SnapInfo directory settings
      url: "/concept-configure-snapinfo-directory-settings.html"
      entries:
      - title: Set up a SnapInfo LUN
        url: "/task-set-up-a-snapinfo-lun.html"
      - title: Change the SnapInfo directory path
        url: "/task-change-the-snapinfo-directory-path.html"
    - title: Configure datasets
      url: "/concept-configure-datasets.html"
      entries:
      - title: Requirements for creating a dataset
        url: "/reference-requirements-for-creating-a-dataset.html"
      - title: Create a dataset
        url: "/task-create-a-dataset.html"
      - title: Modify a dataset
        url: "/task-modify-a-dataset.html"
      - title: View a dataset
        url: "/task-view-a-dataset.html"
      - title: Delete a dataset
        url: "/task-delete-a-dataset.html"
    - title: Configure policies
      url: "/concept-configure-policies.html"
      entries:
      - title: Requirements for adding policies to a dataset
        url: "/reference-requirements-for-adding-policies-to-a-dataset.html"
      - title: Add policies
        url: "/task-add-policies.html"
      - title: Modify policies
        url: "/task-modify-policies.html"
      - title: View policies
        url: "/task-view-policies.html"
      - title: Delete policies
        url: "/task-delete-policies.html"
    - title: Configure SVMs or CIFS servers for Hyper-V over SMB
      url: "/concept-configure-svms-or-cifs-servers-for-hyper-v-over-smb.html"
  - title: Manage reports
    url: "/concept-report-management.html"
    entries:
    - title: View a dataset report
      url: "/task-view-a-report.html"
    - title: View a host report
      url: "/task-view-a-host-report.html"
    - title: Delete a report
      url: "/task-delete-a-report.html"
  - title: VSS components
    url: "/concept-overview-of-vss-components.html"
    entries:
    - title: CSV 2.0 in Windows Server 2012 and later
      url: "/concept-cluster-shared-volume-2-0-architecture.html"
    - title: SMB 3.0 support for Hyper-V VMs in Windows Server 2012
      url: "/reference-smb-3-0-support-hyper-v-vms-in-windows-server-2012.html"
    - title: How SnapManager for Hyper-V uses VSS
      url: "/concept-how-snapmanager-for-hyper-v-uses-vss.html"
    - title: ONTAP VSS Hardware Provider requirement
      url: "/concept-ontap-vss-hardware-provider-requirement.html"
    - title: View installed VSS providers
      url: "/task-view-installed-vss-providers.html"
    - title: Verify that the VSS Hardware Provider was used successfully
      url: "/task-verify-that-the-vss-hardware-provider-was-used-successfully.html"
  - title: Create and manage backup jobs in SnapManager for Hyper-V
    url: "/concept-create-and-manage-backup-jobs-in-snapmanager-for-hyper-v.html"
    entries:
    - title: Requirements for manually backing up a dataset
      url: "/reference-requirements-for-manually-backing-up-a-dataset.html"
    - title: How SnapManager for Hyper-V handles saved-state backups
      url: "/concept-how-snapmanager-for-hyper-v-handles-saved-state-backups.html"
    - title: Manually backing up a dataset
      url: "/task-manually-backing-up-a-dataset.html"
    - title: Monitor backup jobs
      url: "/task-monitor-backup-jobs.html"
    - title: Delete a backup
      url: "/task-delete-a-backup.html"
  - title: Restore a virtual machine from a backup copy
    url: "/concept-restore-a-virtual-machine.html"
    entries:
    - title: Requirements for restoring a virtual machine
      url: "/reference-requirements-for-restoring-a-virtual-machine.html"
    - title: Restore a virtual machine from a backup copy
      url: "/task-restore-a-virtual-machine-from-a-backup-copy.html"
  - title: Perform a cluster operating system rolling upgrade
    url: "/concept-perform-a-cluster-os-rolling-upgrade.html"
    entries:
    - title: Map LUNs in mixed operating system mode
      url: "/task-map-luns-after-the-windows-server-2016-node-addition.html"
    - title: Update the dataset and SnapInfo across all nodes
      url: "/task-update-the-dataset-and-snapinfo-across-all-nodes.html"
  - title: Perform disaster recovery
    url: "/concept-perform-disaster-recovery.html"
    entries:
    - title: Configure SnapManager for Hyper-V for failover
      url: "/concept-configure-snapmanager-for-hyper-v-for-failover.html"
    - title: Recover and restor from a disaster recovery failover
      url: "/task-recover-and-restore-from-a-disaster-recovery-failover.html"
    - title: Reconfigure storage systems after a disaster recovery failback
      url: "/task-reconfigure-storage-systems-after-a-disaster-recovery-failback.html"
    - title: Restore the original configuration for standalone hosts
      url: "/task-restore-the-original-configuration-for-standalone-hosts.html"
    - title: Restore the original configuration for clustered hosts
      url: "/task-restore-the-original-configuration-for-clustered-hosts.html"
  - title: Troubleshoot SnapManager for Hyper-V
    url: "/concept-snapmanager-for-hyper-v-troubleshoot.html"
    entries:
    - title: Backup Failed for the following VM(s) since it cannot be backedup online
        or No VM to be found for backup
      url: "/reference-backup-failed-for-the-following-vm-s-since-it-cannot-be-backedup-online-or-no-vm-to-be-found-for-backup.html"
    - title: Unexpected error querying for the IVssWriterCallback interface. hr = 0x80070005,
        Access is denied.
      url: "/reference-unexpected-error-querying-for-the-ivsswritercallback-interface-hr-0x80070005.html"
    - title: Backup reports use management console time zone information in report name
      url: "/reference-backup-reports-use-management-console-time-zone-information-in-report-name.html"
    - title: Backup and restore notifications not sent in IPv6-only environments
      url: "/reference-backup-and-restore-notifications-not-sent-in-ipv6-only-environments.html"
    - title: Failover clustering event ID 5121
      url: "/reference-failover-clustering-event-id-5121.html"
    - title: Virtual machine backups made while a restore operation is in progress might
        be invalid
      url: "/reference-virtual-machine-backups-made-while-a-restore-operation-is-in-progress-might-be-invalid.html"
    - title: Virtual machine managing itself
      url: "/reference-virtual-machine-adding-itself-to-a-dataset.html"
    - title: Connection time is longer with IPv6-only host
      url: "/reference-connection-time-is-longer-with-ipv6-only-host.html"
    - title: 'Volume Shadow Copy Service error: An internal inconsistency was detected'
      url: "/reference-volume-shadow-copy-service-error-an-internal-inconsistency-was-detected.html"
    - title: Web Service Client channel was unable to connect to the ConfigurationManagementService
        instance on machine smhv51_81clus
      url: "/reference-web-service-client-channel-was-unable-to-connect-to-the-configurationmanagementservice-instance-on-machine-smhv51-81clus.html"
    - title: MSI custom property used in silent installation
      url: "/reference-msi-custom-property-used-in-silent-installation.html"
    - title: SnapManager for Hyper-V is not licensed on the host or in the Storage System
      url: "/reference-snapmanager-for-hyper-v-is-not-licensed-on-the-host-or-in-the-storage-system.html"
    - title: Delete backups after failover
      url: "/reference-secondary-machine-unable-to-delete-backups-after-failover.html"
    - title: Storage performance degrades after failed backup
      url: "/reference-storage-performance-degrades-after-failed-backup.html"
    - title: Deleted SnapInfo Snapshot copies
      url: "/reference-retention-of-snapinfo-snapshot-copies.html"
    - title: High memory consumption caused by antivirus solution
      url: "/reference-high-memory-consumption-caused-by-antivirus-solution.html"
    - title: Space consumption when making two Snapshot copies for each backup
      url: "/reference-space-consumption-when-making-two-snapshot-copies-for-each-backup.html"
    - title: SnapDrive SDDiscoveryFileSystemListInfo response is null while backing
        up
      url: "/reference-error-snapdrive-sddiscoveryfilesystemlistinfo-response-is-null.html"
    - title: 'Error: Vss Requestor - Backup components failed'
      url: "/reference-error-vss-requestor-backup-components-failed.html"
    - title: Vss Requestor - Backup Components failed. An expected disk did not arrive
        in the system
      url: "/reference-error-vss-requestor-backup-components-failed-an-expected-disk-did-not-arrive-in-the-system.html"
    - title: Vss Requestor - Backup Components failed with partial writer error
      url: "/reference-dataset-backup-might-fail-with-a-partial-writer-error.html"
    - title: VSS returns errors against Microsoft iSCSI Target VSS Hardware Provider
        during NAS backup
      url: "/reference-vss-returns-errors-against-microsoft-iscsi-target-vss-hardware-provider-during-nas-backup.html"
    - title: Vss Requestor - Backup Components failed. Failed to call keep snapshot
        set.
      url: "/reference-vss-requestor-backup-components-failed-failed-to-call-keep-snapshot-set.html"
    - title: MBR LUNs unsupported in SnapManager for Hyper-V
      url: "/reference-mbr-luns-unsupported-in-snapmanager-for-hyper-v.html"
    - title: Backup fails after you remove a virtual machine from Hyper-V Manager
      url: "/reference-backup-fails-after-removing-virtual-machine-from-hyper-v-manager.html"
    - title: Some types of backup failures do not result in partial backup failure
      url: "/reference-some-types-of-failures-do-not-generate-error-message.html"
    - title: Restore failure after storage system volume renaming
      url: "/reference-restore-failure-after-storage-system-volume-renaming.html"
    - title: Restore from a backup after failback
      url: "/reference-restore-from-a-backup-after-failback.html"
    - title: Web Service Client channel unable to connect while updating the dataset
        to the new node
      url: "/reference-web-service-client-channel-unable-to-connect-while-updating-the-dataset-to-the-new-node.html"
    - title: Datasets are not automatically replicated to new nodes in a Windows Failover
        Cluster
      url: "/reference-datasets-are-not-automatically-replicated-to-new-nodes-in-a-windows-failover-cluster.html"
    - title: Error 1935. An error occurred during the installation of assembly component
      url: "/reference-error-1935-an-error-occurred-during-the-installation-of-assembly-component.html"
    - title: Backup jobs that involve more than 15 CSVs from the same storage system
        might fail
      url: "/reference-backup-jobs-that-involve-more-than-15-csvs-from-the-same-filer-fail-with-rename-snapshot-error.html"
    - title: Either the specified VM(s) are not present or they cannot be backed up
        online
      url: "/reference-either-the-specified-vm-s-are-not-present-or-they-cannot-be-backed-up-online.html"
    - title: Required hotfix KB2263829 cannot be installed on some platforms
      url: "/reference-required-hotfix-kb2263829-cannot-be-installed-on-some-platforms.html"
    - title: Backup failure with the error &#8220;Shadow copy creation is already in
        progress&#8221;
      url: "/reference-backup-fail-with-the-error-shadow-copy-creation-is-already-in-progress.html"
  - title: Legal notices
    url: /legal-notices.html