---
permalink: reference_either_the_specified_vm_s_are_not_present_or_they_cannot_be_backed_up_online.html
sidebar: sidebar
keywords: vm, present, backed, up, online
summary: Either the specified VM(s) are not present or they cannot be backed up online
---
= Either the specified VM(s) are not present or they cannot be backed up online
:icons: font
:imagesdir: ./media/

* *Message*
+
Either the specified VM(s) are not present or they cannot be backed up online

* *Description*
+
One reason this message occurs is when application-consistent backups fail if the pass-through disk size on the VM is less than 300 MB. Your error log will resemble the following example:
+
----
Log Name:      Application
Source:        SnapMgrServiceHost
Date:          11/12/2012 12:24:28 PM
Event ID:      106
Task Category: Backup Event
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      defiant16.wak-qa.com
Description:
SnapManager for Hyper-V backup failed to complete

Backup Failed for the following VM(s) since it cannot be backedup online or No VM to be found for backup
               VM Name: demovm-0
----
+
There are no other application or system error messages to indicate the failure.

* *Corrective action*
+
You can either resize the pass-through disk to be larger than 300 MB or run the backup with the Allow saved state VM backup option enabled.
+
NOTE: This corrective action is applicable in both SAN and NAS environments.

* *Message*
+
Either the specified VM(s) are not present or they cannot be backed up online

* *Description*
+
A second reason this message occurs is because Windows cannot perform an online backup of this system because the scoped snapshots option for Hyper-V VMs is enabled. Scoped snapshots are mainly used by Windows critical updates.

* *Corrective action*
+
You must disable the scoped snapshots option by creating a DWORD ScopeSnapshots parameter with value 0 in:
+
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\SystemRestore\
+
NOTE: This corrective action is applicable in both SAN and NAS environments.
