---
permalink: reference_virtual_machine_backups_made_while_a_restore_operation_is_in_progress_might_be_invalid.html
sidebar: sidebar
keywords: 
summary: ''
---
= Virtual machine backups made while a restore operation is in progress might be invalid
:icons: font
:imagesdir: ./media/

* *Issue*
+
An application-consistent backup created while a restore operation is in progress might be invalid. Restoring a virtual machine from this incomplete backup results in data loss and the virtual machine is deleted.

* *Cause*
+
The SnapManager for Hyper-V configuration information is missing in the backup copy. The backup operation is successful, but the backup copy is invalid because the virtual machine configuration information is not included. The SnapManager for Hyper-V restore operations delete the virtual machine configuration information from the Hyper-V host before performing a restore operation. This behavior is by design in the Microsoft Hyper-V Writer.

* *Corrective action*
+
Ensure that the backup schedule does not coincide with the restore operation, or that the on-demand backup you want to perform does not overlap with a restore operation on the same data.
