---
permalink: reference-requirements-for-adding-a-hyper-v-parent-host-or-host-cluster.html
sidebar: sidebar
keywords: configuration, information, available, parent, host, cluster, snapmanager, hyper-v
summary: "You must have all necessary configuration information available before adding a parent host or host cluster to SnapManager for Hyper-V."
---
= Requirements for adding a Hyper-V parent host or host cluster
:icons: font
:imagesdir: ./media/

[.lead]
You must have all necessary configuration information available before adding a parent host or host cluster to SnapManager for Hyper-V.

== SnapManager for Hyper-V installation

SnapManager for Hyper-V must be installed on the Hyper-V host that you want to add.

If you do not have SnapManager for Hyper-V installed, you are prompted to run the Remote Host Install wizard. The same SnapManager for Hyper-V version must be installed on each cluster node.

== Configuration settings

The Hyper-V parent host that you want to add must be configured for SnapManager for Hyper-V.

If the SnapInfo settings, report directory settings, and notification settings are not configured for SnapManager for Hyper-V, you can configure them after you add the host, using the Configuration wizard.

Initially, the *Manage Storage Connections* tab is empty. You can add the storage connections from the *Manage Storage Connections* tab, but the newly added connections are visible from SnapDrive for Windows (SDW) Transport Protocol Settings (TPS).

You must configure the backup repository and report directory settings to add and manage virtual machines by using SnapManager for Hyper-V. Notification settings are optional.

== Virtual machines and ONTAP LUNs

All of the files associated with the virtual machines, including configuration files, Snapshot copy file location, and VHDs, must reside on ONTAP LUNs.

This is necessary to perform a successful backup.

NOTE: If you change a virtual machine Snapshot file location to a different ONTAP LUN after creating the virtual machine, you should create at least one virtual machine Snapshot copy using Hyper-V Manager before making a backup by using SnapManager for Hyper-V. If you change the Snapshot copy file location and do not make a virtual machine Snapshot copy before making a backup, the backup operation could fail.

== Dedicated and clustered virtual machines

Your virtual machines can be dedicated or part of a cluster.

If you add a single host, SnapManager for Hyper-V manages the dedicated virtual machines on that host. If you add a host cluster, SnapManager for Hyper-V manages the shared virtual machines on the host cluster. Virtual machines residing on SAN and NAS that belong to the same host cluster should not exist in the same dataset. Adding these types of resources to a single dataset can cause the dataset backup to fail.

For application-consistent backups, dataset backups of clustered virtual machines take longer to complete when the virtual machines run on different nodes of the cluster. When virtual machines run on different nodes, separate backup operations are required for each node in the cluster. If all virtual machines run on the same node, only one backup operation is required, resulting in a faster backup.

== Number of virtual machines

If your Hyper-V host or host cluster has more than 1,000 virtual machines, you must increase the value of the maximum `Elements In Cache Before Scavenging` property in the `SnapMgrServiceHost.exe.config` file for Hyper-V Cache Manager. This value should be greater than or equal to the number of Hyper-V hosts running on a stand-alone host or cluster. The value should be changed on each node of the cluster, and the SnapManager for Hyper-V service must be restarted after changing this value. You must manually edit the `SnapMgrServiceHost.exe.config` file using a text editor.

----
<cacheManagers>
…
      <add name="HyperV Cache Manager"
                        type="Microsoft.Practices.EnterpriseLibrary.Caching.CacheManager,
                           Microsoft.Practices.EnterpriseLibrary.Caching"
                        expirationPollFrequencyInSeconds="60"
                        maximumElementsInCacheBeforeScavenging="1200"
                        numberToRemoveWhenScavenging="10"
                        backingStoreName="inMemory" />
…
</cacheManagers>
----

== SnapManager for Hyper-V service account requirements

When using SnapManager for Hyper-V to manage a Hyper-V host cluster, the SnapManager for Hyper-V and SnapDrive for Windows service accounts must be domain user accounts with local administrator rights on the server.

SnapManager for Hyper-V application-consistent backups run on the cluster node where the virtual machine is running. If Cluster Shared Volumes (CSVs) used by the virtual machine are not owned by the same node, virtual machine backups can fail when the SnapManager for Hyper-V service is using a local system account (even though the account has administrator privileges). In this case, SnapManager for Hyper-V cannot detect that the virtual machine files are residing on a CSV, causing the backup to fail.

NOTE: For remote Volume Shadow Copy Service (VSS) operations with virtual machines stored on clustered Data ONTAP SMB 3.0 continuous availability (CA) shares to work properly, you must grant full control rights to the share for the SnapDrive for Windows service accounts and a minimum read-level access to the SnapManager for Hyper-V web service account.

*Related information*

http://technet.microsoft.com/library/cc753637(WS.10).aspx[Microsoft TechNet: Hyper-V]
