---
permalink: reference_web_service_client_channel_was_unable_to_connect_to_the_configurationmanagementservice_instance_on_machine_smhv51_81clus.html
sidebar: sidebar
keywords: web, service, client, channel, unable, conntect, configurationmanagementservice, instance, machine, smhv51_81clus
summary: Web Service Client channel was unable to connect to the ConfigurationManagementService instance on machine smhv51_81clus.
---
= Web Service Client channel was unable to connect to the ConfigurationManagementService instance on machine smhv51_81clus
:icons: font
:imagesdir: ./media/

* *Message*
+
`Web Service Client channel was unable to connect to the ConfigurationManagementService instance on machine smhv51_81clus.`
+
`There was no endpoint listening at net.tcp://smhv51_81clus/SnapManager/HyperV/ConfigMgmtService/v_10 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.`

* *Description*
+
If you export configuration information, the local Web service port settings of the managed hosts are stored in the exported configuration file. If you later have to reinstall SnapManager for Hyper-V using a different Web service port, and import the former configuration information, you experience connection issues.

* *Corrective action*
+
To prevent this issue, use the same Web service port settings contained in the exported configuration file when reinstalling SnapManager for Hyper-V.
