---
permalink: reference_error_vss_requestor_backup_components_failed.html
sidebar: sidebar
keywords: error, vss, requestor, backup, component, fail
summary: Error: Vss Requestor - Backup components failed.
---
= Error: Vss Requestor - Backup components failed
:icons: font
:imagesdir: ./media/

* *Message*
+
The following error message is displayed in the SnapManager for Hyper-V report and the Windows Event log: Error: Vss Requestor - Backup Components failed. Writer Microsoft Hyper-V VSS Writer involved in backup or restore encountered a retryable error. Writer returned failure code 0x800423f3. Writer state is XXX. For more information, see the Hyper-V-VMMS event log in the Windows Event Viewer.

* *Description*
+
If you receive a VSS retry error that causes your application-consistent backup to fail, SnapManager for Hyper-V retries the backup three times with a wait of one minute between each attempt.

* *Corrective action*
+
You can configure the number of retries (retry count) and the duration of wait time between the retries (retry interval) using the following registry keys:
+
`Key: HKLM\System\CurrentControlSet\Services\OnCommandHyperV\Parameters DWORD value in seconds: vss_retry_sleep (The time duration to wait between retries) DWORD value: vss_retry (Number of retries)`
+
These settings are at the Hyper-V host level and the keys and values should be set on the Hyper-V host for each virtual machine. If the virtual machine is clustered, the keys should be set on each node in the cluster.
+
You must restart SnapManager for Hyper-V after making changes to or adding these registry keys.
