---
permalink: reference_vss_requestor_backup_components_failed_failed_to_call_keep_snapshot_set.html
sidebar: sidebar
keywords: vss, requestor, backup, component, fail, call, snapshot, set
summary: Vss Requestor - Backup Components failed. Failed to call keep snapshot set.
---
= Vss Requestor - Backup Components failed. Failed to call keep snapshot set.
:icons: font
:imagesdir: ./media/

* *Error*
+
`Vss Requestor - Backup Components failed. Failed to call keep snapshot set. Reason Index and count must refer to a location within the string.`

* *Description*
+
This error occurs when VMs in a backup job reside on a Storage Virtual Machine and CIFS server with the same name.

* *Corrective action*
+
None available for this release.

* *Failure example*
 . Create a Storage Virtual Machine and CIFS server with the same name: for example, "`test1`".
 . Add the test1 name to the DNS with both IP addresses.
 . On a Windows Server 2012 host, install SnapManager for Hyper-V and create some VMs using the CIFS shares from test1.
 . Create a backup copy that includes those VMs.
 . Note that the backup job fails with the error `Backup Components failed. Failed to call keep snapshot set. Reason Index and count must refer to a location within the string.`
