---
permalink: reference_backup_fails_after_removing_virtual_machine_from_hyper_v_manager.html
sidebar: sidebar
keywords: 
summary: ''
---
= Backup fails after you remove a virtual machine from Hyper-V Manager
:icons: font
:imagesdir: ./media/

* *Issue*
+
After you remove a Hyper-V virtual machine (VM) from Hyper-V Manager, backup operations fail if you do not update the dataset associated with the VM.

* *Cause*
+
This issue occurs when you remove a Hyper-V VM from Hyper-V Manager and attempt a backup without modifying the dataset. Additionally, if you re-created a VM, you must modify the dataset. SnapManager for Hyper-V creates datasets based on the VM ID (GUID). The backup fails when a VM is deleted, removed, or re-created, which creates a new GUID. Although this does not trigger the failure of the entire backup process, if a VM is deleted, and then re-created with the same name, it is not automatically protected by SnapManager for Hyper-V.

* *Corrective action*
+
Remove the VM from the dataset list of VMs, and add any re-created VMs to the dataset.

*Related information*

xref:concept_configuring_datasets.adoc[Configuring datasets]

xref:task_modifying_a_dataset.adoc[Modifying a dataset]
