---
permalink: reference_command_line_switch_descriptions.html
sidebar: sidebar
keywords: 
summary: 'You can use command line switches to perform a silent installation, which enables you to use an installation script to install SnapManager for Hyper-V.'
---
= List and description of command line switches for silent installation
:icons: font
:imagesdir: ./media/

[.lead]
You can use command line switches to perform a silent installation, which enables you to use an installation script to install SnapManager for Hyper-V.

The following table provides a list of values and describes each of the available command-line installation switches.

|===
| Switch| Value| Description
a|
SILENT_MODE=
a|
1
a|
Enables SnapManager for Hyper-V to properly execute the unattended install feature. This switch is required for first-time installations, upgrades, and complete uninstallations.
a|
REINSTALLMODE=
a|
 
a|
Specifies the reinstall mode to be used.
a|
REINSTALLMODE=
a|
v
a|
Indicates that the installation is run from the source package and that the local package is cached. Do not use this option for first-time installations of SnapManager for Hyper-V. Reinstalls all files regardless of version, date, or checksum value.
a|
REINSTALLMODE=
a|
a
a|
Reinstalls SnapManager for Hyper-V files if older versions are present or if files are missing.
a|
REINSTALLMODE=
a|
o
a|
Indicates that all SnapManager for Hyper-V required registry entries from HKEY_LOCAL_MACHINE and HKEY_CLASSES_ROOT should be rewritten.
a|
REINSTALLMODE=
a|
m
a|
Indicates that all SnapManager for Hyper-V required registry entries from HKEY_CURRENT_USER and HKEY_USERS should be rewritten.
a|
REINSTALLMODE=
a|
u
a|
Reinstalls all shortcuts and recaches all icons, overwriting any existing shortcuts and icons.
a|
REINSTALL=
a|
ALL
a|
Reinstalls all SnapManager for Hyper-V features.
a|
/Li
a|
filename
a|
Specifies that a SnapDrive installation log should be generated.
a|
SMHV_LICENSE=
a|
license
a|
Specifies the appropriate and valid SnapManager for Hyper-V license.
a|
INSTALLDIR=
a|
target installation directory
a|
Specifies the target installation directory to which SnapManager for Hyper-V is installed. This switch is required only when installing SnapManager for Hyper-V for the first time.
a|
SVCUSERNAME=
a|
DOMAIN\username
a|
Specifies the domain and user name that SnapManager for Hyper-V uses during the unattended installation.
a|
SMHVSRV_PASSWORD=
a|
password
a|
Specifies the password for the SMHVSRV_PASSWORD user.
a|
SMHVSRV_CONFIRMUSERPASSWORD=
a|
password
a|
Confirms the password for the SMHVSRV_CONFIRMUSERPASSWORD user.
a|
SMHV_WEBSRV_TCP_PORT
a|
port number
a|
Specifies which port the SnapManager for Hyper-V web service uses for Net.Tcp. The default port is 808.
|===
The following syntax shows a fresh installation:

`setup.exe /s /v"/qn SILENT_MODE=1 /L*v SMHVInstall.log SVCUSERNAME=Domain\User Name SMHVSRV_PASSWORD=password SMHVSRV_CONFIRMUSERPASSWORD=password"`

The following syntax shows an upgrade:

`setup.exe /s /v"/qn REINSTALLMODE=vamus REINSTALL=ALL SILENT_MODE=1 /L*v SMHVUpgrade.log SVCUSERNAME=Domain\User Name SMHVSRV_PASSWORD=password SMHVSRV_CONFIRMUSERPASSWORD=password"`

The following syntax shows an uninstallation:

`Setup.exe /s /x /v"/qn SILENT_MODE=1 /L*v SMHVuninstall.log"`
