---
permalink: reference_requirements_for_remote_host_install.html
sidebar: sidebar
keywords: 
summary: 'Before using the Remote Host Install wizard to remotely install SnapManager for Hyper-V on a host or node, you must gather some required host details.'
---
= Requirements for using the Remote Host Install wizard
:icons: font
:imagesdir: ./media/

[.lead]
Before using the Remote Host Install wizard to remotely install SnapManager for Hyper-V on a host or node, you must gather some required host details.

You can access the Remote Host Install wizard from the Actions pane in the Protection window. It enables you to remotely install or uninstall SnapManager for Hyper-V on standalone and cluster nodes or hosts.

If you add a host that does not have SnapManager for Hyper-V, the Add Host wizard prompts you to install it on the host.

* *Install or Uninstall*
+
You must choose whether to use the wizard to remotely install or uninstall SnapManager for Hyper-V on hosts or nodes.

* *Per Server or Per Storage*
+
You must choose whether to install SnapManager for Hyper-V on a per-server or a per-storage basis.

* *Host Name/IP*
+
You must provide the name or IP address of the host on which you want to install SnapManager for Hyper-V. You can select *Browse...* to browse for the host or node.

* *Port*
+
You must provide the port number to connect to the host or node.

* *SMHV License Key*
+
You must provide the SnapManager for Hyper-V license key.

* *SDW License Key*
+
You must provide the SnapDrive for Windows license key.

* *User Name*
+
You must provide the host or node administrator-level user name using the format domain\username.

* *Password*
+
You must enter the host or node password.

* *Confirm Password*
+
You must reenter the host or node password for confirmation.
