---
permalink: task_restore_a_virtual_machine_from_a_backup_copy.html
sidebar: sidebar
keywords: snapmanager, hyper-v, restore, single, virtual, machine, vm, recover, lost, damage, data, backup, copy, restoring
summary: "You can use SnapManager for Hyper-V, which restores a single virtual machine (VM) at a time, to recover lost or damaged data from a backup copy."
---
= Restore a virtual machine from a backup copy
:icons: font
:imagesdir: ./media/

[.lead]
You can use SnapManager for Hyper-V, which restores a single virtual machine (VM) at a time, to recover lost or damaged data from a backup copy.

You must have the following information available:

* Backup name
* Configuration information
* Script information

When restoring to an alternate host, the CPU type on the physical computer on which your original VM resided should be compatible with the physical computer onto which you want to restore the VM. Alternatively, you can use the Hyper-V Manager to specify that the machine is allowed to restore to a machine with a different CPU type.

After storage live migration, you cannot restore from the latest backup.

If you start a restore operation of a Hyper-V virtual machine, and another backup or restoration of the same virtual machine is in process, it fails.

. From the navigation pane, click *Recovery*.
. Select the virtual machine that you want to restore.
. In the Backups pane, select the name of the backup copy that you want to restore and click *Restore*.
+
The Restore wizard appears.

. Complete the steps in the wizard to restore the virtual machine backup copy.
+
Closing the wizard does not cancel the restore operation. SnapManager for Hyper-V validates the virtual machine configuration before beginning the restore operation. If there have been any changes in the virtual machine configuration, a warning appears, enabling you to choose to continue or to cancel the operation.

You can view the status of the restore operation in the Jobs Management window or check the operation results by viewing the report in the Reports Management window.

*Related information*

xref:reference_restoring_from_a_backup_after_failback.adoc[Restoring from a backup after failback]
