---
permalink: task_change_the_snapinfo_directory_path.html
sidebar: sidebar
keywords: control, snapinfo, directory, path, setting, configuration, wizard, action, changing, change
summary: You can control SnapInfo directory path settings by using the Configuration wizard or the SnapInfo settings action.
---
= Change the SnapInfo directory path
:icons: font
:imagesdir: ./media/

[.lead]
You can control SnapInfo directory path settings by using the Configuration wizard or the *SnapInfo settings* action.

SnapInfo directory settings are specified on the host level in SnapManager for Hyper-V. SnapManager for Hyper-V supports NAS (SMB) hosts and SAN hosts. For SAN hosts, the SnapInfo settings are applied on the volume level; for NAS hosts, the SnapInfo settings are applied on the SMB share level.

If you have added the IP address of the storage system to SnapDrive for Windows TPS, the storage settings from SnapDrive for Windows are automatically populated when you run the configuration wizard in SnapManager for Hyper-V. If you do not have SnapDrive for Windows TPS configured, you must specify the IP address of the storage system in the Manage Storage Connections tab in SnapManager for Hyper-V.

. From the navigation pane, click *Protection* > *Hosts*.
. Select the host for which you want to change the SnapInfo directory path.
. From the Actions pane, select *SnapInfo settings*.
+
The SnapInfo Settings dialog box opens.

. Select the storage type from the options shown:
+
[options="header"]
|===
| Option| Description
a|
SAN
a|
This is the default storage type.
a|
NAS
a|
Use this option for SMB shares.
|===

. Click *Browse*.
+
The Browse for Folder window opens.

. Select your SnapInfo storage system (SAN) or volume (NAS) and click *OK*.
+
The hosts that display are NAS shares corresponding to the storage systems that have been registered using the Manage Storage Connections option at the host level. If you do not see the shares you are looking for, ensure that Manage Storage Connections has been configured correctly.

. From the SnapInfo Settings window, click *OK*.
