---
permalink: task_uninstall_snapmanager_for_hyper_v.html
sidebar: sidebar
keywords: snapmanager, hyper-v, windows, server, control, panel, uninstall, application, operating, system, remote, host, protection
summary: "You can uninstall SnapManager for Hyper-V from the Windows server using the Control Panel uninstall application for your operating system."
---
= Uninstall SnapManager for Hyper-V
:experimental:
:icons: font
:imagesdir: ./media/

[.lead]
You can uninstall SnapManager for Hyper-V from the Windows server using the Control Panel uninstall application for your operating system. You can remotely uninstall SnapManager for Hyper-V on standalone and cluster nodes or hosts using the Remote Host Install wizard from the Actions pane in the Protection window.

.About this task
Uninstalling SnapManager for Hyper-V deletes all datasets and policies. You cannot recover that information after the uninstallation is complete. If you want to save your datasets and host configuration information, you can export them before you uninstall.

.steps
. On the Windows server where you installed SnapManager for Hyper-V, navigate to the Control Panel and select menu:Control Panel[Programs > Programs and Features].
. Scroll through the list of installed programs to find SnapManager for Hyper-V.
. Click the name of the program and then click *Uninstall*.
. When prompted to confirm uninstallation, click *Yes*.

*Related information*

xref:task_importing_or_exporting_host_and_dataset_configuration_information.adoc[Importing or exporting host and dataset configuration information]
