---
permalink: task_importing_or_exporting_host_and_dataset_configuration_information.html
sidebar: sidebar
keywords: manage, host, management, console, multiple, import, export, information, dataset, consistency
summary: Although you should manage a host from only one management console, if you need to do so from multiple consoles, you can import and export host and dataset configuration information from one remote management console to another to ensure data consistency.
---
= Importing or exporting host and dataset configuration information
:icons: font
:imagesdir: ./media/

[.lead]
Although you should manage a host from only one management console, if you need to do so from multiple consoles, you can import and export host and dataset configuration information from one remote management console to another to ensure data consistency.

You should not import or export configuration information to the directory on which SnapManager for Hyper-V is installed. If you uninstall SnapManager for Hyper-V, this file is lost.

NOTE: You can use the Import and Export wizard to change host and dataset configuration settings to a previously exported setting. If you perform this operation in a clustered environment, you must import the settings on all nodes in the cluster so that all host and dataset configurations are the same.

. From the navigation pane, click *Protection*.
. From the Actions pane, click *Import and export*.
+
The Import and Export wizard appears.

. Complete the steps in the wizard to export host and dataset configuration information from one management console to another.
+
NOTE: The export file is static and current only at the time that export file was executed.

. Complete the steps in the wizard to import host and dataset configuration information to the destination management console.
