---
permalink: task_install_snapmanager_for_hyper_v.html
sidebar: sidebar
keywords: install, snapmanager, hyper-v, back, up, restore, data, snapdrive, windows
summary: You can install SnapManager for Hyper-V so that you are able to back up and restore your data. You should install SnapDrive for Windows before installing SnapManager for Hyper-V.
---
= Install SnapManager for Hyper-V
:icons: font
:imagesdir: ./media/

[.lead]
You can install SnapManager for Hyper-V so that you are able to back up and restore your data. You should install SnapDrive for Windows before installing SnapManager for Hyper-V.

.What you'll need
Your existing data must be backed up, and you must have the following information ready:

* License key
* Login credentials
* Port number (default: 808; must match the SnapDrive for Windows installation port number)

.Steps
. Double-click the SnapManager for Hyper-V executable file to launch the SnapManager for Hyper-V installer.
. Select the installation location and click *Next*.
. Complete the steps in the SnapManager for Hyper-V *Install Shield* wizard.
. Click *Install* on the *Ready to Install* page.
. Review the summary of your selections and click *Finish*.

*Related information*

xref:reference_hotfix_requirements_for_windows_server_environments.adoc[Hotfix requirements for Windows Server environments]
